create table public.matches (
  id uuid default gen_random_uuid() primary key,
  created_at timestamptz default now() not null,
  champion text not null,
  role text,
  win boolean not null,
  k_d_a text,
  rank_tier text not null,
  marks_in_division integer not null default 0,
  notes text,
  my_support text,
  enemy_adc text,
  enemy_support text,
  session_id uuid,
  game_duration integer,
  first_blood boolean,
  turret_kills integer,
  vision_score integer,
  premade_with text,
  enemy_top text,
  enemy_jungle text,
  enemy_mid text,
  gold_earned integer,
  damage_dealt integer,
  damage_taken integer,
  cs_at_10 integer,
  objective_participation integer,
  dragons_taken integer,
  barons_taken integer,
  heralds_taken integer
);

alter table public.matches disable row level security;
